#include<bits/stdc++.h>
#include<windows.h>
#include<conio.h>
using namespace std;
int dhp,hp,t,t1,t2,kill,dide,didechenjiu[110],killchenjiu[110],start;
int main()
{
    SetConsoleTitle("勇士之征(2.3.7)");
    cout<<"版本2.3.7(重大更新,优化游戏进入时的界面),感谢洛谷名为明明想fly的用户的贡献,已将其加入贡献殿堂"<<endl<<"作者:zhanghongxiao";
    Sleep(3000);
    system("cls");
    hp=150;
    srand(time(0));
    while(1)
    {
        cout<<"按1查看贡献殿堂,2进入战斗,3查看更新预告,其他数字退出(假如不是数字,后果自负)"<<endl;
        cin>>start;
        if(start==1)
        {
            system("cls");
            start=0; 
            cout<<"洛谷名:明明想fly"<<' '<<' '<<' '<<' '<<"原因:发现BUG"<<endl;
            cout<<"按任意数字退出"; 
            cin>>start;
            system("cls");
        }
        else if(start==2)
        {
            freopen("dhp.txt","r",stdin);
            cin>>dhp;
            cin>>dide;
            cin>>kill;
            for(int i=1;i<=5;i++)
            {
                cin>>didechenjiu[i];
            } 
            for(int i=1;i<=7;i++)
            {
                cin>>killchenjiu[i];
            }
            fclose(stdin);
            system("cls");
            if(!dhp) 
            {
                dhp=40000;
                dide=0;
                kill=0; 
            }
            while(dhp>0)
            {
                if(hp<=0)
                {
                    cout<<"你倒下了!"<<endl;
                    Sleep(3000);
                    system("cls");
                    dide++;
                    if(dide==10)
                    {
                        cout<<"解锁成就:萌新的感觉";
                        didechenjiu[1]=1; 
                        Sleep(4000);
                    }
                    if(dide==50)
                    {
                        cout<<"解锁成就:坚持";
                        didechenjiu[2]=1; 
                        Sleep(4000);
                    }
                    if(dide==100)
                    {
                        cout<<"解锁成就:非常会肝";
                        didechenjiu[3]=1; 
                        Sleep(4000);
                    }
                    if(dide==300)
                    {
                        cout<<"解锁成就:疯狂地肝";
                        didechenjiu[4]=1; 
                        Sleep(4000);
                    }
                    if(dide==1000)
                    {
                        cout<<"解锁成就:一代肝师";
                        didechenjiu[5]=1; 
                        Sleep(4000);
                    }
                    freopen("dhp.txt","w",stdout);
                    cout<<dhp<<endl;
                    cout<<dide<<endl;
                    cout<<kill<<endl; 
                    for(int i=1;i<=5;i++)
                    {
                        cout<<didechenjiu[i]<<endl;
                    } 
                    for(int i=1;i<=7;i++)
                    {
                        cout<<killchenjiu[i]<<endl;
                    } 
                    fclose(stdout);
                    return 0;
                }
                t=rand()%20;
                if(t==0) 
                {
                    cout<<"你回血了！"<<endl;
                    hp=hp+(rand()%50+50);
                    cout<<"你的血:"<<hp;
                    Sleep(1000);
                    system("cls");
                }
                if(t==1||t==2||t==3) 
                {
                    cout<<"你打出暴击了！"<<endl;
                    dhp=dhp-((rand())%10+1)*((rand())%10+1)*((rand())%10+1)*((rand())%5+1);
                    cout<<"怪的血:"<<dhp;
                    Sleep(1000);
                    system("cls");
                }
                if(t==4) 
                {
                    cout<<"你打出天崩地裂：火球术了！"<<endl;
                    dhp=dhp-((rand())%10+1)*((rand())%10+1)*((rand())%10+1)*((rand())%10+1)*((rand())%2+1);
                    t2+=rand()%1+2;
                    cout<<"怪的血:"<<dhp;
                    Sleep(2500);
                    system("cls");
                }
                if(t==5) 
                {
                    cout<<"你打出冰冻术了！"<<endl;
                    dhp=dhp-((rand())%10+1)*((rand())%10+1)*((rand())%8+1);
                    t1+=rand()%1+1;
                    cout<<"怪的血:"<<dhp;
                    Sleep(2500);
                    system("cls");
                }
                if(t==6) 
                {
                    cout<<"你打出雷击术了！"<<endl;
                    dhp=dhp-((rand())%10+1)*((rand())%10+1)*((rand())%10+1)*((rand())%6+1);
                    cout<<"怪的血:"<<dhp;
                    Sleep(2500);
                    system("cls");
                    for(int i=1;i<=7;i++)
                    {
                        dhp=dhp-((rand())%10+1)*((rand())%10+1);
                        cout<<"怪的血:"<<dhp<<endl;
                        Sleep(400);
                    }
                    Sleep(2500);
                    system("cls");
                }
                if(t==7) 
                {
                    cout<<"你打出天崩地裂：集气攻击了！"<<endl;
                    for(int i=1;i<=3;i++)
                    {
                        cout<<"聚气:第"<<i<<"回合"<<endl; 
                        Sleep(800);
                        system("cls");
                        if(!t1)
                        {
                            cout<<"怪物攻击！"<<endl;
                            hp=hp-((rand())%10+1)*((rand())%6+1);
                            cout<<"你的血:"<<hp;
                            Sleep(1000);
                            system("cls");
                        } 
                        else
                        {
                            t1--;
                            cout<<"怪物被冰冻！"<<endl;
                            dhp=dhp-((rand())%20+1);
                            cout<<"怪的血:"<<dhp;
                            Sleep(1000);
                            system("cls");
                        }
                        if(hp<=0)
                        {
                            cout<<"你倒下了!"<<endl;
                            Sleep(3000);
                            system("cls");
                            dide++;
                            if(dide==10)
                            {
                                cout<<"解锁成就:萌新的感觉";
                                didechenjiu[1]=1; 
                                Sleep(4000);
                            }
                            if(dide==50)
                            {
                                cout<<"解锁成就:坚持";
                                didechenjiu[2]=1; 
                                Sleep(4000);
                            }
                            if(dide==100)
                            {
                                cout<<"解锁成就:非常会肝";
                                didechenjiu[3]=1; 
                                Sleep(4000);
                            }
                            if(dide==300)
                            {
                                cout<<"解锁成就:疯狂地肝";
                                didechenjiu[4]=1; 
                                Sleep(4000);
                            }
                            if(dide==1000)
                            {
                                cout<<"解锁成就:一代肝师";
                                didechenjiu[5]=1; 
                                Sleep(4000);
                            }
                            freopen("dhp.txt","w",stdout);
                            cout<<dhp<<endl;
                            cout<<dide<<endl;
                            cout<<kill<<endl; 
                            for(int i=1;i<=5;i++)
                            {
                                cout<<didechenjiu[i]<<endl;
                            } 
                            for(int i=1;i<=7;i++)
                            {
                                cout<<killchenjiu[i]<<endl;
                            } 
                            fclose(stdout);
                            return 0;
                        }
                        if(dhp<=0)
                        {
                            cout<<"你赢了！"<<endl;
                            Sleep(5000);
                            system("cls");
                            kill++;
                            if(kill==1)
                            {
                                cout<<"解锁成就:第一个怪";
                                killchenjiu[1]=1; 
                                Sleep(4000);
                            }
                            if(kill==2)
                            {
                                cout<<"解锁成就:小试牛刀";
                                killchenjiu[2]=1; 
                                Sleep(4000);
                            }
                            if(kill==3)
                            {
                                cout<<"解锁成就:初露锋芒";
                                killchenjiu[3]=1; 
                                Sleep(4000);
                            }
                            if(kill==10)
                            {
                                cout<<"解锁成就:渐入佳境";
                                killchenjiu[4]=1; 
                                Sleep(4000);
                            }
                            if(kill==50)
                            {
                                cout<<"解锁成就:锋芒毕露";
                                killchenjiu[5]=1; 
                                Sleep(4000);
                            }
                            if(kill==100)
                            {
                                cout<<"解锁成就:斩妖除魔";
                                killchenjiu[6]=1; 
                                Sleep(4000);
                            }
                            if(kill==300)
                            {
                                cout<<"解锁成就:妖之克星";
                                killchenjiu[7]=1; 
                                Sleep(4000);
                            }
                            freopen("dhp.txt","w",stdout);
                            cout<<40000<<endl;
                            cout<<dide<<endl;
                            cout<<kill<<endl; 
                            for(int i=1;i<=5;i++)
                            {
                                cout<<didechenjiu[i]<<endl;
                            } 
                            for(int i=1;i<=7;i++)
                            {
                                cout<<killchenjiu[i]<<endl;
                            } 
                            fclose(stdout);
                            return 0;
                        } 
                    }
                    dhp=dhp-(rand()%1000+1)-4000;
                    cout<<"Boom!怪的血:"<<dhp;
                    Sleep(2500);
                    system("cls");
                    if(rand()%20+1==1)
                    {
                        cout<<"由于集气攻击，空气爆炸了"<<endl;
                        Sleep(600);
                        cout<<"磁... ..."<<endl;
                        Sleep(400);
                        cout<<"裂... ..."<<endl;
                        Sleep(400);
                        cout<<"爆... ..."<<endl;
                        Sleep(400);
                        dhp=dhp-15000;
                        cout<<"怪的血:"<<dhp;
                        Sleep(2000);
                        system("cls");
                        cout<<"你倒下了!"<<endl;
                        Sleep(3000);
                        system("cls");
                        dide++;
                        if(dide==10)
                        {
                            cout<<"解锁成就:萌新的感觉";
                            didechenjiu[1]=1; 
                            Sleep(4000);
                        }
                        if(dide==50)
                        {
                            cout<<"解锁成就:坚持";
                            didechenjiu[2]=1; 
                            Sleep(4000);
                        }
                        if(dide==100)
                        {
                            cout<<"解锁成就:非常会肝";
                            didechenjiu[3]=1; 
                            Sleep(4000);
                        }
                        if(dide==300)
                        {
                            cout<<"解锁成就:疯狂地肝";
                            didechenjiu[4]=1; 
                            Sleep(4000);
                        }
                        if(dide==1000)
                        {
                            cout<<"解锁成就:一代肝师";
                            didechenjiu[5]=1; 
                            Sleep(4000);
                        }
                        freopen("dhp.txt","w",stdout);
                        cout<<dhp<<endl;
                        cout<<dide<<endl;
                        cout<<kill<<endl; 
                        for(int i=1;i<=5;i++)
                        {
                            cout<<didechenjiu[i]<<endl;
                        } 
                        for(int i=1;i<=7;i++)
                        {
                            cout<<killchenjiu[i]<<endl;
                        } 
                        fclose(stdout);
                        return 0;
                    } 
                }
                if(t>7) 
                {
                    cout<<"你打出普攻了！"<<endl;
                    dhp=dhp-((rand())%10+1)*((rand())%10+1)*((rand())%8+1);
                    cout<<"怪的血:"<<dhp;
                    Sleep(1000);
                    system("cls");
                }
                if(t2) 
                {
                    t2--;
                    cout<<"怪物被灼烧！"<<endl;
                    dhp=dhp-((rand())%10+1)*((rand())%10+1)*((rand())%4+1);
                    cout<<"怪的血:"<<dhp;
                    Sleep(1000);
                    system("cls");
                }
                if(!t1)
                { 
                    cout<<"怪物攻击！"<<endl;
                    hp=hp-((rand())%10+1)*((rand())%6+1);
                    cout<<"你的血:"<<hp;
                    Sleep(1000);
                    system("cls");
                } 
                else
                {
                    t1--;
                    cout<<"怪物被冰冻！"<<endl;
                    dhp=dhp-((rand())%20+1);
                    cout<<"怪的血:"<<dhp;
                    Sleep(1000);
                    system("cls");
                }
            }
            cout<<"你赢了！"<<endl;
            Sleep(5000);
            system("cls");
            kill++;
            if(kill==1)
            {
                cout<<"解锁成就:第一个怪";
                killchenjiu[1]=1; 
                Sleep(4000);
            }
            if(kill==2)
            {
                cout<<"解锁成就:小试牛刀";
                killchenjiu[2]=1; 
                Sleep(4000);
            }
            if(kill==3)
            {
                cout<<"解锁成就:初露锋芒";
                killchenjiu[3]=1; 
                Sleep(4000);
            }
            if(kill==10)
            {
                cout<<"解锁成就:渐入佳境";
                killchenjiu[4]=1; 
                Sleep(4000);
            }
            if(kill==50)
            {
                cout<<"解锁成就:锋芒毕露";
                killchenjiu[5]=1; 
                Sleep(4000);
            }
            if(kill==100)
            {
                cout<<"解锁成就:斩妖除魔";
                killchenjiu[6]=1; 
                Sleep(4000);
            }
            if(kill==300)
            {
                cout<<"解锁成就:妖之克星";
                killchenjiu[7]=1; 
                Sleep(4000);
            }
            freopen("dhp.txt","w",stdout);
            cout<<40000<<endl;
            cout<<dide<<endl;
            cout<<kill<<endl; 
            for(int i=1;i<=5;i++)
            {
                cout<<didechenjiu[i]<<endl;
            } 
            for(int i=1;i<=7;i++)
            {
                cout<<killchenjiu[i]<<endl;
            } 
            fclose(stdout);
            return 0;
        }
        else if(start==3)
        {
            system("cls");
            start=0; 
            cout<<"即将推出成就殿堂"<<endl;
            cout<<"按任意数字退出"; 
            cin>>start;
            system("cls");
        }
        else
        {
            system("cls");
            return 0;
        } 
    }
}
